#! /bin/bash
# search_number <счёт> <путь к справочнику>
	# номер счёта
schet=$1
	# | sed 's/ *//g')
	# путь к справочнику
#phones=/home/andrew/Work/sms/phones.txt
phones=$2

	# ищем строку с указанным счётом и выводи номер телефон 
	# подразумевается, что одному счёту соответствует один номер или ничего
res=$(cat $phones | grep -m 1 $schet | sed -r 's/(.*)-(.*)/\1/')
#| cut -f1 -d '-'
if [[ -n $res ]]
then
	echo "80$res"
	exit 0
fi
exit 1
