#! /bin/bash
	# убираем пробелы 
schet=$(echo $* | sed 's/ *//g')
	# путь к справочнику
phones=/home/andrew/Work/sms/phones.txt
	# ищем строку с указанным счётом и выводи номер телефон
cat $phones | grep $schet | sed -r 's/(.*)-(.*)/\1/'
#| cut -f1 -d '-'

