#! /bin/bash
# send_kartvit_sms <путь к фалу с суммами> <путь к справочнику телефонов>

# kartvit=$1
#phones=$2
kartvit=/home/andrew/work/sms/sms/kartvit.txt
phones=/home/andrew/work/sms/phones.txt
s=0
e=0

echo "start send..."
echo "[$(date +%D\ \-\ %T)]----------------------------------" >> sms_kartvit.log
	# если нужный файл существует
if [ -e $kartvit ];
then
		# получаем список номеров и сумм (каждая строка вида 'номер-сумма' - отдельное сообщение)
		# перебираем строки и отправляем СМС
	tmp_file=$(./scan_kartvit $kartvit $phones)
	while read line
	do
			# разбиваем строку по словам и выделяем номер и сумму
		arr=($line)
		dst=${arr[0]}
		mess=${arr[1]}
			# отправляем СМС
		./send $dst $mess
			# проверяем результат отправки и выводим соответствующее сообщение
		if [[ $? -eq 0 ]]
		then
			echo "	$dst - OK" | tee -a  sms_kartvit.log
			s=$(($s + 1))
		else
			echo "	$dst - ERR"  | tee -a  sms_kartvit.log
			e=$(($e + 1))
		fi
        done < $tmp_file

	rm $tmp_file

        echo "  Complete:  errors: $e; success: $s" | tee -a sms_kartvit.log
	echo "---------------------------------------------[$(date +%T)]" >> sms_kartvit.log
		# удаляем файл после обработки
	rm $kartvit

	exit 0
else
	echo "	Complete:  nothing to do" | tee -a  sms_kartvit.log
	echo "---------------------------------------------[$(date +%T)]" >> sms_kartvit.log

	exit 11
fi



